### ISSUE TITLE
How do I change the style of the generated image

### ISSUE THREAD

**Issue by vincentgc** [NVlabs/SPADE#25]
Hi, you did a great job. 
I know that the generated images can show different style using gauGAN, but how can I reproduce the function?

**Comment by vincentgc** [comment]
Do I need to train different models from scratch if I want to obtain some images with different styles?

**Comment by code-de** [comment]
And how to change a style of a generated image if I trained a model with VAE?

**Comment by taesungp** [comment]
To produce outputs with different styles, you need to train with VAE by using `--use_vae` flag. It it was not trained with VAE, it cannot generate different styles. 

The pretrained models of COCO, ADE20K and Cityscapes are all without VAE, because we actually didn't want random generation of styles, in order to keep the evaluation metric reproducible. 

As you know. for GauGAN video, we trained with VAE. 

Once you finish training with VAE, to produce different styles for the same semantic layout input, simply run the model multiple times. It will always generate different results.
