### ISSUE TITLE
meaning of contain_dontcare_label

### ISSUE THREAD

**Issue by lzhbrian** [NVlabs/SPADE#45]
Hi, thanks for the code.
I have questions about the `contain_dontcare_label` arg.

I saw this is set to True on COCO, ade20k, yet set to False on facades, custom, and not set in cityscapes.

Is this related to the __label's index (0-based or 1-based)__?
Or is this related to if the datasets' contains __background__ label?

Thanks in advance.

**Comment by taesungp** [comment]
The dataset sometimes contains `unknown` label, or unlabeled area. When these pixels exist, they mark the class of these pixels as `0`, `-1`, or `255`. `--contain_dontcare_label` is supposed to take care of this. 

It is somewhat related to label's index (0-based or 1-based), because the starting index may depend on whether the dataset contains `unknown` label. It is not related to the existence of background label, because `unknown` label may contain foreground pixels as well. 

After all, when the label input is loaded, the meaningful classes should be zero-indexed.

**Comment by lzhbrian** [comment]
Thanks!
